#!/usr/bin/env node

/**
 * 自动生成 hooks 导出代码
 * 扫描 src/useXxx/index.ts 并生成 src/index.ts
 */

import { readdirSync, statSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = resolve(__filename, '..')

const srcDir = resolve(__dirname, '../src')
const indexPath = resolve(srcDir, 'index.ts')

console.log('🔍 Scanning hooks...\n')

// 获取所有 use* 目录
const hookDirs = readdirSync(srcDir).filter((dir) => {
  const fullPath = resolve(srcDir, dir)
  return dir.startsWith('use') && statSync(fullPath).isDirectory()
})

if (hookDirs.length === 0) {
  console.log('No hooks found in src directory.')
  process.exit(0)
}

console.log(`Found ${hookDirs.length} hook(s):\n`)

// 生成导出代码
const exports = []
const typeExports = []

hookDirs.forEach((hookName) => {
  const hookIndexPath = resolve(srcDir, hookName, 'index.ts')

  if (!existsSync(hookIndexPath)) {
    console.warn(`⚠️  Warning: ${hookName}/index.ts not found, skipping...`)
    return
  }

  console.log(`✅ ${hookName}`)

  // 导出函数/类
  exports.push(`export { ${hookName} } from './${hookName}'`)

  // 尝试导出类型（从 index.ts 中查找类型导出）
  typeExports.push(`export type * from './${hookName}'`)
})

// 生成文件内容
const content = `// Auto-generated by scripts/generate-exports.js
// Do not edit this file manually
// Run "pnpm generate" to regenerate

${exports.join('\n')}
${typeExports.length > 0 ? '\n' + typeExports.join('\n') : ''}
`

// 写入文件
writeFileSync(indexPath, content, 'utf-8')

console.log(`\n✨ Generated ${indexPath}`)
console.log(`   Total: ${exports.length} export(s)\n`)
