/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    JsxExample: typeof import('./../src/components/JsxExample.jsx')['default']
    TsxExample: typeof import('./../src/components/TsxExample.tsx')['default']
    VanButton: typeof import('vant/es')['Button']
    VueUseExample: typeof import('./../src/components/VueUseExample.vue')['default']
  }
}

// For TSX support
declare global {
  const JsxExample: typeof import('./../src/components/JsxExample.jsx')['default']
  const TsxExample: typeof import('./../src/components/TsxExample.tsx')['default']
  const VanButton: typeof import('vant/es')['Button']
  const VueUseExample: typeof import('./../src/components/VueUseExample.vue')['default']
}